# Generated by Django 2.2.6 on 2019-10-19 17:14

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('address', models.TextField()),
                ('landmark', models.CharField(max_length=75)),
                ('country', models.CharField(max_length=25)),
                ('state', models.CharField(max_length=25)),
                ('city', models.CharField(max_length=25)),
                ('postal_code', models.CharField(max_length=6)),
                ('point_of_contact', models.EmailField(max_length=254)),
                ('poc_mobile', models.CharField(max_length=12)),
                ('poc_name', models.CharField(max_length=100)),
                ('telephone', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('is_active', models.BooleanField(default=True)),
                ('website', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Unit_types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_type', models.CharField(max_length=25)),
                ('area_in_sq', models.FloatField()),
                ('descrption', models.TextField(max_length=100, verbose_name='unit_type_descrption')),
                ('is_active', models.BooleanField(default=True, verbose_name='unit_type_is_active')),
                ('for_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.Property_Info')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_no', models.CharField(max_length=5)),
                ('wing', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=25)),
                ('descrption', models.TextField(max_length=100, verbose_name='unit_descrption')),
                ('is_active', models.BooleanField(default=True, verbose_name='unit_is_active')),
                ('unit_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.Unit_types')),
            ],
        ),
    ]
