# Generated by Django 2.2.6 on 2019-10-19 18:42

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property_info',
            name='description',
            field=models.TextField(help_text='More Information of Property - Optional', null=True),
        ),
        migrations.AlterField(
            model_name='property_info',
            name='landmark',
            field=models.CharField(max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='property_info',
            name='telephone',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31, null=True),
        ),
        migrations.AlterField(
            model_name='property_info',
            name='website',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='status',
            field=models.CharField(help_text='Shows status - Occupied/Vacant', max_length=25, null=True),
        ),
    ]
