# Generated by Django 2.2.6 on 2019-10-19 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_auto_20191020_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='status',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='property.Unit_status'),
        ),
    ]
