# Generated by Django 2.2.3 on 2019-10-22 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_auto_20191020_0032'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property_Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=25, unique=True)),
                ('uom', models.CharField(help_text='Unit of Measurement', max_length=20, null=True)),
                ('description', models.TextField()),
            ],
        ),
    ]
